#! /bin/sh

export GTK_THEME=Catppuccin-Mocha-Standard-Blue-Dark
export XCURSOR_THEME=Catppuccin-Mocha-Dark-Cursors
export XCURSOR_SIZE=24

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config window_gap 10
bspc config split_ratio 0.52
bspc config gapless_monocle false
bspc config border_width 2 

bspc config automatic_scheme longest_side
bspc config initial_polarity first_child
bspc config focus_follows_pointer true

bspc config normal_border_color  "#434c5e"
bspc config active_border_color  "#88c0d0"
bspc config focused_border_color "#b48ead"

bspc rule -a kitty state=tiled 
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=tiled 

pkill picom
picom --config ~/.config/picom/picom.conf &

nitrogen --restore &
polybar &
darkman run & 

xsetroot -cursor_name left_ptr &
xrandr --output DP-0 --primary --output HDMI-0 --right-of DP-0
feh --bg-fill ~/Downloads/wallpaper/cloudblue.jpg
